name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test code
        run: |
          go test
  code_quality:
    name: Code Quality
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout cod
        uses: actions/checkout@v2
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
