name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test code
        run: |
          go test
